database/models/__init__.py
from .meme import Meme

database/models/meme.py
from database.db import db

class Meme(db.Model):
    """Базовая моделька мема
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)

    def __repr__(self) -> str:
        return f"{self.name}"

app.py
from flask import Flask, Blueprint, render_template
from src.meme import meme_blueprint
from database.db import db

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:postgres@172.17.0.2:5432/memesearcher'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


db.init_app(app)

main_blueprint = Blueprint('', __name__, url_prefix='')

@main_blueprint.route('/', methods=("GET",))
def home():
    return render_template('main.html')

app.register_blueprint(main_blueprint)
app.register_blueprint(meme_blueprint)

src/meme/__init__.py
from .views import meme_blueprint

src/meme/views.py
import os
import random

from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect, secure_filename

from .crud import create_meme, delete_meme_by_name, get_all_memes

_ALLOWED_FORMATS = [".svg", ".jpg", ".png"]

meme_blueprint = Blueprint('meme', __name__, url_prefix='/meme')


@meme_blueprint.route('/', methods=("GET", "POST"))
def meme():
    if request.method == "GET":
        return render_template('meme/create.html')

    file = request.files["file"]

    if not file.filename:
        return render_template('meme/create.html', message="No file!")

    if os.path.splitext(file.filename)[1] not in _ALLOWED_FORMATS:
        return render_template('meme/create.html',
                               message="File not in allowed format!")

    create_meme(file.filename)

    filename = secure_filename(file.filename)
    file.save(os.path.join("static/images", filename))

    return render_template('meme/create.html', message="Successfull created!")


@meme_blueprint.route('/all', methods=("GET", ))
def all_memes():
    return render_template('meme/all.html', memes=get_all_memes())


@meme_blueprint.route('/random', methods=("GET", ))
def random_memes():
    meme_list = get_all_memes()
    random_memes = random.sample(meme_list, 2)

    return render_template('meme/all.html', memes=random_memes)


@meme_blueprint.route('/delete', methods=("DELETE", "POST"))
def delete_meme(*args, **kwargs):
    meme_name = request.form["meme_name"]
    delete_meme_by_name(meme_name)
    return redirect(url_for("meme.all_memes"))

templates/main.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memesearcher</title>
</head>

<body>
    <h1>Meme searcher!</h1> <br>
    <ul>
        <li><a class="action" href="{{ url_for('meme.random_memes') }}">Random memes!</a></li>
        <li><a class="action" href="{{ url_for('meme.meme') }}">Create</a></li>
        <li><a class="action" href="{{ url_for('meme.all_memes') }}">Meme list</a></li>
        <li><a class="action" href="{{ url_for('home') }}">Main</a></li>
    </ul>
    {% block content %}

    {% endblock %}
</body>

</html>

templates/meme/all.html
{% extends 'main.html' %}
{% block content %}

<h3>Meme list...</h3>
{% for meme in memes %}
<img src= {{ url_for('static', filename = "images/"+meme.name) }} width="300"><br>
<form action="{{ url_for('meme.delete_meme') }}" method="POST">
    <input type="text" name="meme_name" value="{{ meme.name }}" hidden><br>
    <button type="submit">Delete meme</button>
</form>
{% endfor %}
{% endblock %}

templates/meme/create.html
{% extends 'main.html' %}
{% block content %}

<h3>Input you meme...</h3>
<form method=post enctype=multipart/form-data>
    <input type=file name=file>
    <input type=submit value=Upload>
</form> 

{% if message %}
    <p>{{message}}</p>
{% endif %}
{% endblock %}